version: '3.8'

services:
  backend:
    build: ./backend  
    ports:
      - "8080:8080"  
    volumes:
      - ./backend/src:/app/src 
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434/api/generate
    restart: unless-stopped

  frontend:
    build: ./frontend 
    ports:
      - "3000:80"     
    depends_on:
      - backend       
    restart: unless-stopped